language: node_js
node_js:
  - "node"
addons:
  ssh_known_hosts: pixore.albizures.com
before_install:
  - bash _scripts/install.sh
script:
  - npm run build
after_success:
  - npm run semantic-release